name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-macOS-arm:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        run: brew install luajit --HEAD

      - name: Build
        run: |
          make -j$(sysctl -n hw.physicalcpu)
          mkdir -p MonaBin/MonaServer
          mkdir -p MonaBin/lib
          cp MonaBase/lib/*.dylib MonaBin/lib
          cp MonaCore/lib/*.dylib MonaBin/lib
          cp -r MonaServer/www MonaServer/*.pem MonaServer/MonaServer MonaTiny/MonaTiny MonaServer/MonaServer.ini MonaBin/MonaServer

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-arm
          path: MonaBin

  build-macOS-x64:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@master

      - name: Install Deps
        shell: arch -x86_64 bash -e {0}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo >> /Users/runner/.bash_profile
          echo 'eval "$(/usr/local/bin/brew shellenv bash)"' >> /Users/runner/.bash_profile
          eval "$(/usr/local/bin/brew shellenv bash)"
          brew install luajit --HEAD && brew install openssl

      - name: Build
        shell: arch -x86_64 bash -e {0}
        run: |
          eval "$(/usr/local/bin/brew shellenv bash)"
          CXX="arch -x86_64 g++" make -j$(sysctl -n hw.physicalcpu)
          mkdir -p MonaBin/MonaServer
          mkdir -p MonaBin/lib
          cp MonaBase/lib/*.dylib MonaBin/lib
          cp MonaCore/lib/*.dylib MonaBin/lib
          cp -r MonaServer/www MonaServer/*.pem MonaServer/MonaServer MonaTiny/MonaTiny MonaServer/MonaServer.ini MonaBin/MonaServer
          
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: MonaServer-macOS-x64
          path: MonaBin
          
      - name: Unit Tests
        shell: arch -x86_64 bash -e {0}
        run: |
          cp -r ../MonaBin/lib ..
          codesign --verbose=4 --force --sign - ../lib/libMonaBase.dylib
          codesign --verbose=4 --force --sign - ../lib/libMonaCore.dylib
          codesign --verbose=4 --force --sign - UnitTests
          ./UnitTests -m=all || true && xattr -rc .
          ./UnitTests -m=all || true && xattr -rc .
          ./UnitTests -m=all || true && xattr -rc .
          ./UnitTests -m=all
          cat UnitTests.log/0.log
        working-directory: UnitTests/

  build-windows:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@master
        
        - name: Setup VSC
          uses: TheMrMilchmann/setup-msvc-dev@v3
          with:
            arch: x64

        - name: Build
          run: |
            msbuild Mona.sln
            mkdir MonaBin
            cp -r MonaServer/www MonaBin/
            cp MonaServer/*.pem MonaBin/
            cp MonaServer/debug/MonaServer.exe MonaBin/
            cp MonaTiny/debug/MonaTiny.exe MonaBin/
            cp MonaServer/MonaServer.ini MonaBin/
            cp MonaServer/External/lib64/lua51.dll MonaBin/

        - name: Upload Artifact 
          uses: actions/upload-artifact@v4
          with: 
            name: MonaServer-Win
            path: MonaBin

        - name: Unit Tests
          run: |
            cp debug\* .
            .\UnitTests.exe -m=all
            cat UnitTests.log/0.log
          working-directory: UnitTests/

          
  build-linux:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@master

          - name: Install Deps
            run: |
              git clone https://github.com/LuaJIT/LuaJIT.git
              cd LuaJIT
              make -j$(nproc) && sudo make install

          - name: Build
            run: |
              make -j$(nproc)
              mkdir -p MonaBin/MonaServer
              mkdir -p MonaBin/MonaBase/lib
              mkdir -p MonaBin/MonaCore/lib
              cp MonaBase/lib/*.so MonaBin/MonaBase/lib
              cp MonaCore/lib/*.so MonaBin/MonaCore/lib
              cp -r MonaServer/www MonaServer/*.pem MonaServer/MonaServer MonaTiny/MonaTiny MonaServer/MonaServer.ini MonaBin/MonaServer

          - name: Upload Artifact 
            uses: actions/upload-artifact@v4
            with: 
              name: MonaServer-Linux
              path: MonaBin

          - name: Unit Tests
            run: |
              ./UnitTests -m=all
              cat UnitTests.log/0.log
            working-directory: UnitTests/
            
